### ISSUE TITLE
t/signedcookies.t fails (with newer HTTP::Cookies?)

### ISSUE THREAD

**Issue by eserte** [ap/Plack-Middleware-SignedCookies#2]
The test suite started to fail on my smokers:
```
#   Failed test 'Own cookies are recognized'
#   at t/signedcookies.t line 51.
#          got: 'c0=;ch=dolor sit\;cs=amet, consectetur;cx='adipiscing elit''
#     expected: 'c0=;cb=lorem "ipsum";ch=dolor sit\;cs=amet, consectetur;cx='adipiscing elit''

#   Failed test 'Tampered cookies are rejected'
#   at t/signedcookies.t line 54.
#          got: 'c0=;ch=dolor sit\;cs=amet, consectetur'
#     expected: 'c0=;cb=lorem "ipsum";ch=dolor sit\;cs=amet, consectetur'
# Looks like you failed 2 tests of 17.
t/signedcookies.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/17 subtests 
```
Statistical analysis suggests that this happens since HTTP::Cookies 6.05 (@oalders: FYI):
```
****************************************************************
Regression 'mod:HTTP::Cookies'
****************************************************************
Name           	       Theta	      StdErr	 T-stat
[0='const']    	      1.0000	      0.0000	10765784633744040.00
[1='eq_6.03']  	      0.0000	      0.0000	   2.63
[2='eq_6.04']  	      0.0000	      0.0000	   4.66
[3='eq_6.05']  	     -1.0000	      0.0000	-5382892316872020.00
[4='eq_6.07']  	     -1.0000	      0.0000	-6808880048294560.00
[5='eq_6.08']  	     -1.0000	      0.0000	-9323442984494490.00

R^2= 1.000, N= 150, K= 6
****************************************************************
```

**Comment by ap** [comment]
Correct. HTTP::Cookies >= 6.05 indiscriminately applies RFC&#160;2965 version=1 parsing rules to any and all cookies with no check for whether the cookie specifies version 1 or even whether it was sent in a `Set-Cookie2` header (rather than `Set-Cookie`, which is not even defined in the RFC but only in the older informal Netscape cookie spec).

**Comment by oalders** [comment]
@ap is this the code change you're referring to? libwww-perl/HTTP-Cookies#49

**Comment by ap** [comment]
Yup. At the very least that parsing should not apply to `Set-Cookie` cookies since [the Netscape spec](https://curl.haxx.se/rfc/cookie_spec.html) doesn’t define anything other than splitting on semicolons. You’ll note that libwww-perl/HTTP-Cookies#32 is very specific about this being an issue for version 1 cookies, which is only a thing in RFC&#160;2965, which only defines `Set-Cookie2`. I was going to file an issue for that.

(It’s also not yet clear to me that the parsing is RFC-compliant. Is stripping double-quotes from the middle of a cookie value that isn’t quoted as a whole actually what the RFC says to do? I think not, but I have to do more due diligence on that.)

(I also have further issues to consider. I’m not sure how I never bothered to support `Set-Cookie2` cookies in this middleware. And since HTTP::Cookies is only a test-time dependency for this module, I wonder if it even makes sense to pull it in. So I have to dig into and then decide on a whole list of points here…)

**Comment by ap** [comment]
Dropping some relevant references here so I can close a few tabs:

* https://curl.se/rfc/cookie_spec.html
* https://www.rfc-editor.org/rfc/rfc2965
* https://www.rfc-editor.org/rfc/rfc2616#page-17
* https://www.rfc-editor.org/rfc/rfc6265
* https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis/

**Comment by ap** [comment]
It’s been 3 years. Time to take this out the back and bury it. 1.204 is on its way to the CPAN with a switch to HTTP::CookieJar for the tests which makes this bogus test failure disappear because that module parses cookies correctly.

Thank you @eserte for the report.
